# Site settings
title: Goodrichs.net
email: glenn@goodrichs.net
description: "4. Loud. Kids."
baseurl: ""
url: "https://goodrichs.net"

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Glenn"
      comments: true
collections:
  xmas:
    output: true
