# Site settings
title: Goodrichs.net 
email: glenn@goodrichs.net
description: "4. Loud. Kids."
baseurl: ""
url: "http://goodrichs.github.io"

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Glenn"
      comments: true

